import { Dish, SideDish, DishCategory } from './types';

// export const BUDGET_LIMIT = 400; // Removed: Prices and budget limits are no longer used

export const SIDE_DISHES: SideDish[] = [
  { id: 'no_garnish', name: 'Без гарнира' },
  { id: 'grilled_vegetables', name: 'Овощи гриль' },
  { id: 'rice_with_vegetables', name: 'Рис с овощами' },
  { id: 'boiled_rice', name: 'Рис отварной' },
  { id: 'mashed_potatoes', name: 'Картофельное пюре' },
  { id: 'baked_potatoes', name: 'Запеченный картофель' },
  { id: 'steamed_vegetables', name: 'Овощи на пару' },
  { id: 'bulgur', name: 'Булгур' },
  { id: 'grechka', name: 'Гречка'},
  { id: 'spaghetti', name: 'Спагетти' }, // добавлен новый гарнир
  { id: 'ptitim', name: 'Паста пти-тим' }, // добавлен новый гарнир
];

const ALL_SIDE_IDS = SIDE_DISHES.map(s => s.id);

export const MENU_ITEMS: Dish[] = [
  // Салаты
  { id: 'salad_beef_liver', name: 'Салат с говяжьей печенью', category: DishCategory.SALAD },
  { id: 'salad_mimosa', name: 'Салат "Мимоза"', category: DishCategory.SALAD },
  { id: 'salad_krab', name: 'Салат "Крабовый"', category: DishCategory.SALAD },
  { id: 'salad_grouse_nest', name: 'Салат "Гнездо глухаря"', category: DishCategory.SALAD },
  { id: 'salad_health', name: 'Салат «Здоровье»', category: DishCategory.SALAD },
  { id: 'salad_spring', name: 'Салат весенний', category: DishCategory.SALAD },
  { id: 'salad_pineapple', name: 'Салат с ананасом', category: DishCategory.SALAD },
  { id: 'salad_caesar_chicken', name: 'Салат "Цезарь с курицей"', category: DishCategory.SALAD },
  { id: 'salad_eggplant_cheese', name: 'Салат с баклажанами и творожным сыром', category: DishCategory.SALAD },
  { id: 'salad_greek', name: 'Салат "Греческий"', category: DishCategory.SALAD },
  { id: 'salad_beans', name: 'Салат с фасолью', category: DishCategory.SALAD },
  { id: 'salad_bulgur', name: 'Салат с булгуром', category: DishCategory.SALAD },
  { id: 'salad_pancake', name: 'Салат блинный', category: DishCategory.SALAD },
  { id: 'salad_herring_fur_coat', name: 'Салат "Сельдь под шубой"', category: DishCategory.SALAD },
  { id: 'salad_baked_vegetables', name: 'Салат из овощей печеных', category: DishCategory.SALAD },
  { id: 'salad_olivier', name: 'Салат "Оливье"', category: DishCategory.SALAD },
  { id: 'salad_vinaigrette', name: 'Салат "Винегрет"', category: DishCategory.SALAD },
  { id: 'salad_beet_cheese', name: 'Салат свекла с сыром', category: DishCategory.SALAD },
  { id: 'salad_fresh_cabbage', name: 'Салат со свежей капустой', category: DishCategory.SALAD },
  { id: 'salad_egg_chicken_sous_vide', name: 'Салат с яйцом, Грудкой Су-вид', category: DishCategory.SALAD },
  { id: 'salad_layered_chicken_liver', name: 'Салат слоеный с куриной печенью', category: DishCategory.SALAD },
  { id: 'salad_krab', name: 'Салат Крабовый', category: DishCategory.SALAD },
  { id: 'salad_baked_vegetables', name: 'Салат из овощей печеных', category: DishCategory.SALAD },
  { id: 'salad_pineapple_chicken', name: 'Салат с ананасом и курицей', category: DishCategory.SALAD },
  { id: 'salad_caesar_chicken', name: 'Салат Цезарь с курицей', category: DishCategory.SALAD },
  { id: 'salad_vegetables', name: 'Салат овощной', category: DishCategory.SALAD },
  { id: 'salad_snack', name: 'Салат Закусочный', category: DishCategory.SALAD },
  // Горячее и супы
  { id: 'soup_borscht_chicken', name: 'Борщ с курицей', category: DishCategory.HOT_DISH },
  { id: 'soup_broccoli_puree', name: 'Суп пюре брокколи', category: DishCategory.HOT_DISH },
  { id: 'soup_noodle_chicken', name: 'Суп лапша домашняя с курицей', category: DishCategory.HOT_DISH },
  { id: 'soup_solyanka_meat', name: 'Солянка мясная', category: DishCategory.HOT_DISH },
  { id: 'soup_mushroom_puree', name: 'Суп пюре из грибов', category: DishCategory.HOT_DISH },
  { id: 'hot_sous_vide_breast_grilled_veg', name: 'Грудка Су-вид с овощами гриль', category: DishCategory.HOT_DISH },
  { id: 'soup_pea', name: 'Суп гороховый', category: DishCategory.HOT_DISH },
  { id: 'hot_chicken_meatballs_garnish', name: 'Тефтели куриные с гарниром', category: DishCategory.HOT_DISH, availableSideIds: ['mashed_potatoes', 'spaghetti'] },
  { id: 'hot_schnitzel_chicken', name: 'Шницель куриный', category: DishCategory.HOT_DISH, availableSideIds: ['mashed_potatoes', 'steamed_vegetables'] },
  { id: 'hot_soba_chicken', name: 'Соба с курицей', category: DishCategory.HOT_DISH },
  { id: 'hot_liver_stroganoff_garnish', name: 'Печень по-строгановски', category: DishCategory.HOT_DISH, availableSideIds: ['mashed_potatoes', 'ptitim', 'grechka'] },
  { id: 'hot_plov_pork', name: 'Плов со свининой', category: DishCategory.HOT_DISH },
  { id: 'hot_manti_sauce', name: 'Манты с соусом', category: DishCategory.HOT_DISH },
  { id: 'hot_meat_french_style', name: 'Мясо по-французски', category: DishCategory.HOT_DISH },
  { id: 'hot_chicken_appetizing', name: 'Курица аппетитная', category: DishCategory.HOT_DISH },
  { id: 'hot_liver_stroganoff', name: 'Печень по-строгановски', category: DishCategory.HOT_DISH },
  { id: 'hot_orzo_mushrooms', name: 'Паста орзо с грибами', category: DishCategory.HOT_DISH },
  { id: 'hot_pasta_bolognese', name: 'Паста болоньезе', category: DishCategory.HOT_DISH },
  { id: 'hot_chicken_breast_sauce', name: 'Грудка куриная в соусе', category: DishCategory.HOT_DISH },
  { id: 'hot_fish_cutlet', name: 'Котлета рыбная', category: DishCategory.HOT_DISH },
  { id: 'hot_potato_asian_chicken', name: 'Картофель по азиатски с курицей', category: DishCategory.HOT_DISH },
  { id: 'hot_plov_meat', name: 'Плов с мясом', category: DishCategory.HOT_DISH },
  { id: 'hot_strips', name: 'Стрипсы', category: DishCategory.HOT_DISH },
  { id: 'hot_lasagna', name: 'Лазанья', category: DishCategory.HOT_DISH },
  { id: 'hot_sous_vide_breast', name: 'Грудка Су-вид', category: DishCategory.HOT_DISH },
  { id: 'hot_chicken_breast_ginger', name: 'Грудка куриная в имбире', category: DishCategory.HOT_DISH },
  { id: 'hot_wings', name: 'Крылья', category: DishCategory.HOT_DISH },
  { id: 'hot_liver_patties', name: 'Оладьи из печени', category: DishCategory.HOT_DISH },
  { id: 'hot_chicken_cutlet_garnish', name: 'Котлета куриная с гарниром', category: DishCategory.HOT_DISH, availableSideIds: ['mashed_potatoes', 'ptitim', 'grechka'] },
  { id: 'hot_lyulya_kebab', name: 'Люля-кебаб', category: DishCategory.HOT_DISH },
  { id: 'hot_stuffed_pepper_meat', name: 'Перец фаршированный с мясом', category: DishCategory.HOT_DISH },
  { id: 'hot_cabbage_roll_meat_garnish', name: 'Голубец с мясом с гарниром', category: DishCategory.HOT_DISH },
  { id: 'hot_homemade_cutlet', name: 'Котлета домашняя', category: DishCategory.HOT_DISH },
  { id: 'hot_fried_chicken_liver', name: 'Печень куриная жареная', category: DishCategory.HOT_DISH },
  { id: 'hot_fish_meatball', name: 'Тефтелька рыбная', category: DishCategory.HOT_DISH },
  { id: 'hot_sausages', name: 'Колбаски', category: DishCategory.HOT_DISH },
  { id: 'hot_zucchini', name: 'Кабачок', category: DishCategory.HOT_DISH },
  { id: 'dessert_trifle_snickers', name: 'Трайфл сникерс (тирамису)', category: DishCategory.HOT_DISH },
  { id: 'dessert_trifle_cherry', name: 'Трайфл вишня (тирамису)', category: DishCategory.HOT_DISH },
  { id: 'soup_mushroom_home', name: 'Суп грибной по домашнему', category: DishCategory.HOT_DISH },
  { id: 'soup_cabbage_fresh', name: 'Суп щи со свежей капустой', category: DishCategory.HOT_DISH },
  { id: 'hot_plov_meat', name: 'Плов с мясом', category: DishCategory.HOT_DISH },
  { id: 'hot_chicken_meatballs_garnish', name: 'Тефтели куриные', category: DishCategory.HOT_DISH, availableSideIds: ['spaghetti', 'grechka'] },
  { id: 'hot_schnitzel_chicken', name: 'Шницель куриный', category: DishCategory.HOT_DISH, availableSideIds: ['mashed_potatoes', 'steamed_vegetables'] },
  { id: 'hot_soba_chicken', name: 'Соба с курицей ', category: DishCategory.HOT_DISH },
  { id: 'hot_goulash', name: 'Гуляш  из курицы', category: DishCategory.HOT_DISH, availableSideIds: ['mashed_potatoes', 'boiled_rice'] },
  { id: 'hot_medovik', name: 'Медовик', category: DishCategory.HOT_DISH },
  { id: 'hot_panna_cotta_strawberry', name: 'Десерт панна-котта с малиной', category: DishCategory.HOT_DISH },

  // Одно блюдо
  { id: 'single_risotto_shrimp', name: 'Ризотто с креветкой', category: DishCategory.SINGLE_DISH },
  { id: 'single_meat_french_chicken', name: 'Мясо по-французски (курица)', category: DishCategory.SINGLE_DISH },
  { id: 'single_twister_chicken', name: 'Твистер с курицей и овощами в сырной лепешке', category: DishCategory.SINGLE_DISH },
  { id: 'hot_fish_baked_vegetables', name: 'Рыба с овощами', category: DishCategory.SINGLE_DISH },
  { id: 'hot_kiev_cutlet', name: 'Котлета по киевски', category: DishCategory.SINGLE_DISH },
  { id: 'hot_pasta_carbonara', name: 'Паста карбонара', category: DishCategory.SINGLE_DISH },
  { id: 'hot_pasta_shrimp', name: 'Паста с креветкой', category: DishCategory.SINGLE_DISH },
  { id: 'single_fish_batter_garnish', name: 'Рыба в кляре', category: DishCategory.SINGLE_DISH, availableSideIds: ['mashed_potatoes', 'boiled_rice'] },
  { id: 'single_pasta_carbonara', name: 'Паста карбонара', category: DishCategory.SINGLE_DISH },
  { id: 'single_pavlova', name: 'Десерт Павловой', category: DishCategory.SINGLE_DISH },
];

export const DEPARTMENTS: string[] = [
  'Финансовый отдел',
  'Развитие сети',
  'Снабжение',
  'Тренеры по кофе',
  'Маркетинг',
  'HR+Университет',
  'IT Отдел',
  'Отдел напитки',
];

// Новый актуальный список для заказов (currentMenu)
export const currentMenu = {
  "Салаты": [
    { id: 'salad_krab', name: 'Салат Крабовый'},
    { id: 'salad_baked_vegetables', name: 'Салат из овощей печеных'},
    { id: 'salad_pineapple_chicken', name: 'Салат с ананасом и курицей'},
    { id: 'salad_caesar_chicken', name: 'Салат Цезарь с курицей'},
    { id: 'salad_vegetables', name: 'Салат овощной'},
    { id: 'salad_snack', name: 'Салат Закусочный'},
  ],
  "Горячее": [
    { id: 'soup_mushroom_home', name: 'Суп грибной по домашнему'},
    { id: 'soup_cabbage_fresh', name: 'Суп щи со свежей капустой'},
    { id: 'hot_plov_meat', name: 'Плов с мясом'},
    { id: 'hot_chicken_meatballs_garnish', name: 'Тефтели куриные'},
    { id: 'hot_schnitzel_chicken', name: 'Шницель куриный',},
    { id: 'hot_soba_chicken', name: 'Соба с курицей '},
    { id: 'hot_goulash', name: 'Гуляш  из курицы'},
    { id: 'hot_medovik', name: 'Медовик'},
    { id: 'hot_panna_cotta_strawberry', name: 'Десерт панна-котта с малиной'},
  ],
  "Одно блюдо": [
    { id: 'hot_pasta_shrimp', name: 'Паста с креветкой'},
  ]
};